export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

}

export const userConstants = {    
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',

}